### ISSUE TITLE
Package website and files in an OVA

### ISSUE THREAD

**Issue by jcanales** [k8-proxy-glacier/k8-website-mass-file-download#12]
Package the website and the files in an HTTP container running in an OVA.

**Comment by jcanales** [comment]
Here are al HTML/CSS/JS files scrapped. 

[www.gov.uk.zip](https://github.com/filetrust/k8-website-mass-file-download/files/5224603/www.gov.uk.zip)

**Comment by belwase** [comment]
Files are located inside VPS on location /home/ubuntu/gov_uk.zip
